create table usuarios (
    id number generated by default as identity primary key,
    nombre_usuario varchar2(50) not null,
    clave varchar2(150) not null

);

select * from usuarios;

drop table usuarios;