CREATE TABLE inventario (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(50),
    tipo VARCHAR2(30),
    cantidad NUMBER,
    precio_costo NUMBER
);

CREATE TABLE habitaciones (
    numero NUMBER PRIMARY KEY,
    capacidad NUMBER,
    estado VARCHAR2(20)
);

CREATE TABLE clientes (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(50),
    telefono VARCHAR2(20),
    nacionalidad VARCHAR2(30),
    habitacion_numero NUMBER REFERENCES habitaciones(numero)
);

CREATE TABLE usuarios (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(50),
    telefono VARCHAR2(20),
    ubicacion VARCHAR2(30)
);

CREATE TABLE recepcionistas (
    id NUMBER PRIMARY KEY REFERENCES usuarios(id)
);

CREATE TABLE boletas (
    folio NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id NUMBER REFERENCES clientes(id),
    usuario_id NUMBER REFERENCES usuarios(id)
);
