import oracledb

class ConexionOracle:
    def __init__(self, usuario: str, password: str, url: str):
        self.usuario = usuario
        self.password = password
        self.url = url
        self.connection = None

    def conectar(self):
        try:
            self.connection = oracledb.connect(
                user=self.usuario,
                password=self.password,
                dsn=self.url
            )
            print("[INFO]: Conectado a BD correctamente.")
        except oracledb.DatabaseError as e:
            error, = e.args
            print(f"[ERROR]: No se pudo conectar a BD → {error.message}")

    def desconectar(self):
        if self.connection:
            self.connection.close()
            print("[INFO]: Conexión a BD cerrada correctamente.")

    def obtener_cursor(self):
        if not self.connection:
            self.conectar()
        return self.connection.cursor()

class Inventario:
    def __init__(self, conexion: ConexionOracle):
        self.conexion = conexion

    def crear_tabla(self):
        cursor = self.conexion.obtener_cursor()
        cursor.execute("""
            CREATE TABLE inventario (
                id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                nombre VARCHAR2(50),
                tipo VARCHAR2(30),
                cantidad NUMBER,
                precio_costo NUMBER
            )
        """)
        self.conexion.connection.commit()

    def insertar(self, nombre, tipo, cantidad, precio_costo):
        cursor = self.conexion.obtener_cursor()
        cursor.execute("""
            INSERT INTO inventario (nombre, tipo, cantidad, precio_costo)
            VALUES (:1, :2, :3, :4)
        """, (nombre, tipo, cantidad, precio_costo))
        self.conexion.connection.commit()

    def listar(self):
        cursor = self.conexion.obtener_cursor()
        cursor.execute("SELECT * FROM inventario")
        return cursor.fetchall()

class Habitacion:
    def __init__(self, conexion: ConexionOracle):
        self.conexion = conexion

    def crear_tabla(self):
        cursor = self.conexion.obtener_cursor()
        cursor.execute("""
            CREATE TABLE habitacion (
                numero NUMBER PRIMARY KEY,
                cantidad_personas NUMBER,
                estado VARCHAR2(20)
            )
        """)
        self.conexion.connection.commit()

    def insertar(self, numero, cantidad_personas, estado):
        cursor = self.conexion.obtener_cursor()
        cursor.execute("""
            INSERT INTO habitacion (numero, cantidad_personas, estado)
            VALUES (:1, :2, :3)
        """, (numero, cantidad_personas, estado))
        self.conexion.connection.commit()

    def listar(self):
        cursor = self.conexion.obtener_cursor()
        cursor.execute("SELECT * FROM habitacion")
        return cursor.fetchall()

class Cliente:
    def __init__(self, conexion: ConexionOracle):
        self.conexion = conexion

    def crear_tabla(self):
        cursor = self.conexion.obtener_cursor()
        cursor.execute("""
            CREATE TABLE cliente (
                id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                nombre VARCHAR2(50),
                telefono VARCHAR2(20),
                nacionalidad VARCHAR2(30),
                habitacion NUMBER REFERENCES habitacion(numero)
            )
        """)
        self.conexion.connection.commit()

    def insertar(self, nombre, telefono, nacionalidad, habitacion):
        cursor = self.conexion.obtener_cursor()
        cursor.execute("""
            INSERT INTO cliente (nombre, telefono, nacionalidad, habitacion)
            VALUES (:1, :2, :3, :4)
        """, (nombre, telefono, nacionalidad, habitacion))
        self.conexion.connection.commit()

    def listar(self):
        cursor = self.conexion.obtener_cursor()
        cursor.execute("SELECT * FROM cliente")
        return cursor.fetchall()

class Usuario:
    def __init__(self, nombre, telefono):
        self.nombre = nombre
        self.telefono = telefono

class Recepcionista(Usuario):
    def __init__(self, conexion: ConexionOracle):
        self.conexion = conexion

    def crear_tabla(self):
        cursor = self.conexion.obtener_cursor()
        cursor.execute("""
            CREATE TABLE recepcionista (
                id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                nombre VARCHAR2(50),
                telefono VARCHAR2(20),
                ubicacion VARCHAR2(50)
            )
        """)
        self.conexion.connection.commit()

    def insertar(self, nombre, telefono, ubicacion):
        cursor = self.conexion.obtener_cursor()
        cursor.execute("""
            INSERT INTO recepcionista (nombre, telefono, ubicacion)
            VALUES (:1, :2, :3)
        """, (nombre, telefono, ubicacion))
        self.conexion.connection.commit()

    def listar(self):
        cursor = self.conexion.obtener_cursor()
        cursor.execute("SELECT * FROM recepcionista")
        return cursor.fetchall()

class Boleta:
    def __init__(self, conexion: ConexionOracle):
        self.conexion = conexion

    def crear_tabla(self):
        cursor = self.conexion.obtener_cursor()
        cursor.execute("""
            CREATE TABLE boleta (
                folio NUMBER PRIMARY KEY,
                cliente_id NUMBER REFERENCES cliente(id),
                usuario_id NUMBER REFERENCES recepcionista(id)
            )
        """)
        self.conexion.connection.commit()

    def insertar(self, folio, cliente_id, usuario_id):
        cursor = self.conexion.obtener_cursor()
        cursor.execute("""
            INSERT INTO boleta (folio, cliente_id, usuario_id)
            VALUES (:1, :2, :3)
        """, (folio, cliente_id, usuario_id))
        self.conexion.connection.commit()

    def listar(self):
        cursor = self.conexion.obtener_cursor()
        cursor.execute("SELECT * FROM boleta")
        return cursor.fetchall()